# Generated by Django 4.0.6 on 2022-07-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.TextField(null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('subs', models.IntegerField(null=True)),
                ('kids', models.TextField(null=True)),
                ('animals', models.TextField(null=True)),
                ('tematika', models.TextField(null=True)),
                ('tg_id', models.CharField(max_length=50)),
                ('apruve', models.BooleanField(null=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
