# Generated by Django 3.2.8 on 2022-09-05 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_alter_user_animals_alter_user_kids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('Муж', 'm'), ('Жен', 'w')], max_length=10, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='user',
            name='tema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.tema', verbose_name='Тематика(выбор)'),
        ),
    ]
