# Generated by Django 4.0.6 on 2022-09-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_alter_user_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('count', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Статистика',
            },
        ),
    ]
