# Generated by Django 4.0.6 on 2022-09-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_remove_user_tematika'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
